### PR TITLE
Remove XLIFF namespace from embedded HTML.

### PR DESCRIPTION
**Pull request by pocmo**
For https://github.com/mozilla-mobile/focus-android/issues/4868

CC @mathjazz.

### CODE REVIEW

**Review by mathjazz — APPROVED** [review]
LGTM.

Something else is wrong with these strings, though. Take a look at Amharic for example:
https://github.com/mozilla-l10n/android-l10n/pull/341/files#diff-24e8ed44d2ba1b8aa390c48898fc7b77e8208ea79a794a2b64a0ff56c2aefd9c

It doesn't look any better in Pontoon:
https://mozilla-pontoon-staging.herokuapp.com/am/focus-for-android-next/all-resources/?string=223364

Seems like some encoding issue, which we don't have in e.g. Fenix:
https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-mobile/fenix/app/src/main/res/values-zh-rTW/strings.xml#L1307

I'm fine with merging this if that works better for you, because the patch does what it should do and the issue a pointed out seems unrelated.

**Comment by mathjazz** [comment]
There are 13 strings with CDATA that need to be translated, and they are all rather long, so I'd like to try to keep them translated. It seems like I can help with that by migrating translations from the old project in Pontoon, because they look OK there.

[OLD](https://mozilla-pontoon-staging.herokuapp.com/sq/focus-for-android/all-resources/?string=163947) vs. [NEW](https://mozilla-pontoon-staging.herokuapp.com/sq/focus-for-android-next/all-resources/?string=223437).

Any chance you could remove translations of those strings from the repo first, so we don't even import them into the DB and mess with the Translation Memory? It's all strings that have CDATA sections in any localizable file, basically the same that this PR is touching.

Also, how hard would it be to remove the trailing newlines and spaces after `<![CDATA[` and leading newlines and spaces before `]]` in the source file? That would make the [new source string](https://mozilla-pontoon-staging.herokuapp.com/sq/focus-for-android-next/all-resources/?string=223437) as readable as it was in the [old format](https://mozilla-pontoon-staging.herokuapp.com/sq/focus-for-android/all-resources/?string=163947), which would help locales that haven't translated these strings yet.

**Comment by pocmo** [comment]
> Any chance you could remove translations of those strings from the repo first, so we don't even import them into the DB and mess with the Translation Memory?

This means we would need to remove those strings with CDATA (in translations) from all locales, right?

> Also, how hard would it be to remove the trailing newlines and spaces after <![CDATA[ and leading newlines and spaces before ]] in the source file?

I can do this. I'd do that in the Focus repository and the changes will end up here via the import PR.

**Comment by pocmo** [comment]
> > Also, how hard would it be to remove the trailing newlines and spaces after <![CDATA[ and leading newlines and spaces before ]] in the source file?
> 
> I can do this. I'd do that in the Focus repository and the changes will end up here via the import PR.

Looking more closely, I think we can even remove most of them. They are translations for the error pages, but those are not in Focus anymore and are coming from A-C now that we switched to the component. I'll investigate and update the strings or remove them as needed.

**Comment by mathjazz** [comment]
> This means we would need to remove those strings with CDATA (in translations) from all locales, right?

Correct!

> Looking more closely, I think we can even remove most of them. They are translations for the error pages, but those are not in Focus anymore and are coming from A-C now that we switched to the component. I'll investigate and update the strings or remove them as needed.

That's even better!

**Comment by pocmo** [comment]
Closing this since most of those strings get removed in the quarantine PR now: https://github.com/mozilla-l10n/android-l10n/pull/338

**Pull request closed without merging**
