### PR TITLE
Import fenix quarantine

### PR DESCRIPTION
**Pull request by mozilla-pontoon**
Import fenix quarantine

### CODE REVIEW

**Comment by mozilla-pontoon** [comment]
Run ID: 6646541155
Authors:  @Amejia481

## TOML file: firefox.toml

### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml

**ID**: `addon_ga_message_body`
**Text**: `Check out 100+ new extensions that let you make Firefox your own.`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**Total errors not yet reported:** 1

**Comment by Amejia481** [comment]
Firefox was intentionally hard coded as it will be used by the nimbus messaging, which doesn't have the ability of replacing string variables.

**Comment by Delphine** [comment]
Hi Arturo! Yes I'm on it right now, adding an exception to the linter 🙂  Thanks

**Review by Delphine — APPROVED** [review]
LGTM. Finishing up the linter part and then will merge. Thanks

**Pull request merged**
