### PR TITLE
add Turkish (tr) localization of Android L10n

### PR DESCRIPTION
**Pull request by fevziomurtekin**
I did a localization study on Turkish. Updates will come.

### CODE REVIEW

**Comment by Pike** [comment]
Asking Delphine for input. We update translations through https://pontoon.mozilla.org/, but we might be able to use this PR to get things started.

Delphine is probably gonna get back to you sometime next week.

**Comment by Delphine** [comment]
Thanks for your contribution!
As stated in the README, localization should not happen in this repo, but on Pontoon.
We also need the Turkish localizer to first accept that we add Fenix to the Turkish team's ongoing work. I'll follow up about this offline. thanks

**Comment by Delphine** [comment]
Got in touch with Selim, who is the manager of Turkish locale.
@fevziomurtekin: in the meantime, if you'd like to check out Pontoon and create an account there, here is the documentation https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html

**Comment by fevziomurtekin** [comment]
I'il be in touch in a few days with Selim. I opened a pontoon account.  I'll analyze to pontoon.

**Comment by Delphine** [comment]
Closing this as I've taken care of things in mozilla-l10n/android-l10n#67
thanks!

**Pull request closed without merging**
