### PR TITLE
Clean up Focus translations

### PR DESCRIPTION
**Pull request by pocmo**
This PR:
* Removes strings from translations that we have removed from the source (`values/strings.xml`)
* Drops translations that contain entities (`&#4768;`) and that are unusable in that form.

CC @mathjazz

### CODE REVIEW

**Comment by mathjazz** [comment]
> Drops translations that contain entities (`&#4768;`) and that are unusable in that form.

`&#4768;` is just an example, right?

The patch looks good.

Removing XLIFF namespace from embedded HTML is insufficient, though. Extra double quotes are added in these translations. I think the safest and easiest bet is to delete these translations completely. Since we changed the source strings, perfect matches will be suggested by the Translation Memory.

https://github.com/mozilla-l10n/android-l10n/blob/aed3c30fcc6497efd66bc4648bf6763671967e81/mozilla-mobile/focus-android/app/src/main/res/values-sl/strings.xml#L199-L202

**Comment by pocmo** [comment]
> &#4768; is just an example, right?

Yeah, just an example.

> Removing XLIFF namespace from embedded HTML is insufficient, though. Extra double quotes are added in these translations. 

Ugh. Android ignores them afaik, but of course we do not want them in the new system.

> I think the safest and easiest bet is to delete these translations completely. Since we changed the source strings, perfect matches will be suggested by the Translation Memory.

Alright, I'll drop all translations with CDATA blocks.

**Comment by pocmo** [comment]
@mathjazz I updated the PR and dropped all translations that contained a CDATA section.

**Review by mathjazz — APPROVED** [review]
Looks great!

https://mozilla-pontoon-staging.herokuapp.com/projects/focus-android-346-2/

@Delphine I can set up the project and migrate all data today.

**Review by Delphine — APPROVED** [review]

**Pull request merged**
