### PR TITLE
Adding Hebrew to Focus

### PR DESCRIPTION
**Pull request by Delphine**
Hebrew already in a-c .TOML file, so only adding to the specific Focus l10n.toml file
CC @ItielMaN . Once this lands I can add Hebrew to Focus for Android

### CODE REVIEW

**Comment by Delphine** [comment]
Ok pause on this. Seems like Focus for Android was already available for Hebrew previously and did not sync back to Pontoon.
Could this be a story of locale code mapping? Fenix Android team use "values-iw" in Fenix for Hebrew.
Is this also an issue here? Or that might affect other locales? Going to investigate more
CC @mathjazz

**Comment by flodolo** [comment]
> Could this be a story of locale code mapping?

That seems likely. At this point, that might not be a problem: the files are in VCS, so I expect that enabling it in Pontoon after this merges will resurrect all the content with the right history and attribution.

**Review by flodolo — APPROVED** [review]

**Comment by flodolo** [comment]
There are 99 locale folders in `res` and we have 97 locales, so there's 2 missing. One is `iw` (Hebrew), the other one is `in` (looks like Indonesian looking at the file).

**Comment by flodolo** [comment]
BTW, if it helps, getting the list of locales from Pontoon is relatively easy via API

```
wget -qO- 'https://pontoon.mozilla.org/graphql?query={project(slug:%22focus-for-android%22){name,localizations{locale{code}}}}' | jq '.data.project.localizations|map(.locale.code)'
```

For GitHub folders it's a lot harder, although I'm sure someone more familiar with jq can do better

```
wget -qO- https://api.github.com/repos/mozilla-l10n/android-l10n/git/trees/master?recursive=1 | jq -c '.tree | map(select(.path | contains("mozilla-mobile/focus-android/app/src/main/res/values-"))) | map(.path | ltrimstr("mozilla-mobile/focus-android/app/src/main/res/values-") | rtrimstr("/strings.xml"))  | map(sub("-r";"-"))'
```

**Comment by Delphine** [comment]
I think this is what needed to be done to add Indonesian back

**Review by flodolo — APPROVED** [review]

**Pull request merged**
