### PR TITLE
Use sat instead of sat-Olck for Santali locale

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Comment by flodolo** [comment]
Did you mean to also update the TOML files in this pull request? I think it would make sense to have them all in the same commit.

**Review by flodolo — CHANGES_REQUESTED** [review]
You're missing all the other files, and I think also the TOML file.

```
./mozilla-mobile/android-components/components/browser/awesomebar/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/browser/engine-system/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/browser/errorpages/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/browser/menu2/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/browser/toolbar/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/browser/menu/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/support/ktx/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/support/migration/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/lib/crash/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/tabs/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/awesomebar/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/app-links/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/webnotifications/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/addons/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/contextmenu/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/qr/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/customtabs/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/sitepermissions/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/readerview/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/findinpage/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/pwa/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/prompts/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/downloads/src/main/res/values-b+sat+Olck
./mozilla-mobile/android-components/components/feature/privatemode/src/main/res/values-b+sat+Olck
```

Let me know if you need help with this, since it should be easy to rename via script.

**Comment by Delphine** [comment]
Oh darn, no I didn't think of it that way.
I wouldn't mind some help since I'm not sure how to go about this quickly. thank you!

**Comment by flodolo** [comment]
@Delphine 
Can you double check?

**Comment by Delphine** [comment]
Both look good, thank you!

**Review by flodolo — APPROVED** [review]
Leaving the actual merge to you

**Comment by Delphine** [comment]
Shouldn't the files contained [within the other folders here](https://github.com/mozilla-l10n/android-l10n/tree/master/mozilla-mobile/android-components/components) be renamed as well?
Or is updating only the ones under lib/crash/src/main/res like you did enough? Just want to be extra sure

**Comment by flodolo** [comment]
They are already renamed. What are you seeing still mentioning the old code?
e.g. https://github.com/Delphine/android-l10n/tree/rename_sat/mozilla-mobile/android-components/components/browser/awesomebar/src/main/res

**Comment by flodolo** [comment]
Also: this PR modifies 28 files (26+2 TOML). That matches the 26 files available in Pontoon.

**Comment by Delphine** [comment]
Ok good, seems like all the folders I was thinking about were contained in main/res so all is good. thanks

**Pull request merged**
