### PR TITLE
Import fenix quarantine

### PR DESCRIPTION
**Pull request by mozilla-pontoon**
Import fenix quarantine

### CODE REVIEW

**Comment by sarah541** [comment]
> Run ID: 6535627772 Authors: @sarah541
> ## TOML file: firefox.toml
> ### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml
> 
> **ID**: `juno_onboarding_enable_notifications_description_nimbus_2` **Text**: `Securely send tabs between your devices and discover other privacy features in Firefox.` **Errors:**
> 
>     * Hard-coded brand `Firefox`. Use a variable instead.
> 
> 
> **ID**: `juno_onboarding_enable_notifications_title_nimbus_2` **Text**: `Notifications help you stay safer with Firefox` **Errors:**
> 
>     * Hard-coded brand `Firefox`. Use a variable instead.
> 
> 
> **ID**: `juno_onboarding_sign_in_description_2` **Text**: `When you\'re signed in and synced, you\'re safer. Firefox encrypts your passwords, bookmarks, and more.` **Errors:**
> 
>     * Incorrect straight quote character `'`. use `’` instead.
> 
>     * Hard-coded brand `Firefox`. Use a variable instead.
> 
> 
> **Total errors not yet reported:** 4

As for the error :  `Text: When you\'re signed in and synced, you\'re safer. Firefox encrypts your passwords, bookmarks, and more.`, has been fixed [here](https://github.com/mozilla-mobile/firefox-android/pull/4109)
And for the errors that say :  `Hard-coded brand Firefox. Use a variable instead.`, Nimbus experiments do not support string placeholders. That's why the comment has been added Note: The word "Firefox" should NOT be translated

**Comment by mozilla-pontoon** [comment]
Run ID: 6549241572
Authors:  @ekager @tiftran

## TOML file: firefox.toml

### File: mozilla-mobile/fenix/app/src/main/res/values/strings.xml

**ID**: `preference_search_address_bar_fx_suggest`
**Text**: `Address bar - Firefox Suggest`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**ID**: `preference_search_learn_about_fx_suggest`
**Text**: `Learn more about Firefox Suggest`
**Errors:**
- Hard-coded brand `Firefox`. Use a variable instead.

**Total errors not yet reported:** 2

**Comment by tiftran** [comment]
Hi @Delphine! I was advised to tag you to get your opinion regarding "Firefox Suggest". Since Firefox Suggest is a branch and we don't want be "Nightly Suggest" or "Firefox Beta Suggest". What is the write way to achieve that?

**Comment by Delphine** [comment]
Hi @tiftran! Sorry, I'm not sure I understand the question.
Firefox Suggest has been called "Firefox suggest" across platforms at this point: https://transvision.mozfr.org/?recherche=Firefox+Suggest&repo=all_projects&sourcelocale=en-US&locale=fr&search_type=strings
Is there a reason we wouldn't want to call it this way?

**Comment by Delphine** [comment]
Update: Fixed the linter/brand part. Now doing another review pass

**Review by Delphine — APPROVED** [review]

**Pull request merged**
