### PR TITLE
Firefox tv quarantine

### PR DESCRIPTION
**Pull request by Pike**
This ties back to https://github.com/mozilla-l10n/android-l10n/pull/63#discussion_r313028269, I think.

Needs an ID change now?

### CODE REVIEW

**Comment by Delphine** [comment]
Darn, I merged yesterday, thought that all had already been taken care of.
Yes, it does need an ID change now. Sorry!
CC @dnarcese about this.

**Comment by dnarcese** [comment]
The id change has been merged https://github.com/mozilla-mobile/firefox-tv/commit/ac97b98001b11da1ed3c8f955d5e24a49a506696

**Comment by dnarcese** [comment]
I think we will be needing to add one more string - which should be added in the next few hours. Can we wait for that change before merging? I will comment here when it is in master.

**Comment by Pike** [comment]
I won't update this PR until European mid-of-day.

Also, we update the strings on a continuous basis. It's not like if you miss this PR you will be out of luck. The next update is just a few days away.

**Comment by dnarcese** [comment]
Understood, we are just trying to get the new string in asap :)

**Comment by dnarcese** [comment]
New  string  is  here: https://github.com/mozilla-mobile/firefox-tv/commit/b845e5368f5058e25db3a29b7ddbe589db395f51

**Pull request merged**
