### PR TITLE
Firefox reality quarantine

### PR DESCRIPTION
**Pull request by Pike**
This is our initial Quarantine for FxR.

@Delphine, this will want a review, on top of the one that I've done earlier today.

### CODE REVIEW

**Comment by Pike** [comment]
IIRC, this would be the changes after we did the first pass: https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine

**Comment by Delphine** [comment]
* "settings_privacy_security": better to call out what "&amp;" will be replaced with here.
* "settings_privacy_policy": string ID is changed although string remains the same. Want to make sure that is expected?
[L275](https://github.com/mozilla-l10n/android-l10n/compare/fe18cda7f6f82a76f60641399d2606f9bfe25023...FirefoxReality-quarantine#diff-5bf7ef0fb54e59bdde826c6df99abe87R275): seems like there is a missing string there
* developer_options_env_offworld: probably better to give a small explanation of what "Offworld" is like so translators know how to translate it correctly
* security_options_permissions_title: I think it's ok to keep the branding here, but just want to call out that "Firefox" is localizable here. Your call
* "privacy_options_reset": better to call out what "&amp;" will be replaced with here
* "homepage_hint": same heads-up about branding here

Gonna file issue in Reality GitHub now.

**Comment by Pike** [comment]
> "settings_privacy_security": better to call out what "&" will be replaced with here.

I think our integration with pontoon will just abstract this away. I expect localizers to see plain `&` instead of `&amp;`

**Comment by Delphine** [comment]
Ok will udpate the issue with that! thanks

**Comment by philip-lamb** [comment]
OK, I've responded to the review in https://github.com/MozillaReality/FirefoxReality/issues/1089 and filed a pull request to fix the minor issues raised in https://github.com/MozillaReality/FirefoxReality/pull/1090. Once that is landed you will want to update this pull request.

**Pull request merged**
