### PR TITLE
Bug 1786793 - part 1: Copy l10n.toml from android-components to firef…

### PR DESCRIPTION
**Pull request by JohanLorenzo**
…ox-android

Fixes https://firefox-ci-tc.services.mozilla.com/tasks/cVc2pFRER2CHbVY2X-kSRQ/runs/0/logs/public/logs/live.log#L40 
Blocks https://github.com/mozilla-l10n/android-l10n-tooling/pull/47

### CODE REVIEW

**Comment by flodolo** [comment]
Is this just for testing the automation in parallel, or is the proposed final solution? 

This would require us to move over translations from the current android-components, and migrate all strings in Pontoon's DB to avoid losing pending suggestions and attribution, which is something we would like to avoid. 
Ideally, automation should keep using the existing TOML files and paths.

**Comment by JohanLorenzo** [comment]
Hey @flodolo!

At the moment, we just want to test automation in parallel so `android-components` must remain the same. That said, after the switch over in ~10 days, we do want `mozilla-mobile/firefox-android/` to be the new source of truth. How big of an issue would that be on your end? cc @csadilek

**Comment by JohanLorenzo** [comment]
> @Delphine will need to sync the work with @mathjazz, since for both Fenix and Focus you'll need to [...] 

For the record, in ~10 days, we will just migrate `android-components` to https://github.com/mozilla-mobile/firefox-android. Fenix and Focus won't move yet. Does this first move impact Fenix and Focus? (I'm sorry, I'm still piecing the android l10n infra together - my understanding is still little).

**Comment by Delphine** [comment]
Hey there! Just a couple things:
* I understood by talking to a few folks in the past weeks that the mono repo would not affect the android-l10n repo. Maybe @escapewindow has ideas on how to avoid touching it? (sorry for putting you on the spot Aki)
Flod also mentions here that in the ideal situation, we keep using the existing TOML files and paths. Is this really not possible?

* Migration in 10 days: I understood nothing would happen until the end of the year. If we need to get @mathjazz involved, I am unsure that we have cycles on both our ends to meet that deadline, unfortunately :/ 

Going to chat with Matjaz about this and we will circle back shortly. thanks!

**Comment by escapewindow** [comment]
My current guesses, without knowing either side of the code very deeply:
1. we may be able to hack around the paths on the android-l10n-tooling side, as in mozilla-l10n/android-l10n-tooling#48
2. we may be able to hack around the paths on the pontoon side
3. It's possible that these hacks (1 and 2), if they work, are best as short-term workarounds to meet the migration deadline and we should schedule a proper migration to the new paths.
4. It's also quite possible that the hacks create more of a mess than they're worth, and delaying the migration until we can migrate pontoon as well would be the best course.

Let's see what Johan finds in mozilla-l10n/android-l10n-tooling#48. If someone is able to look at the pontoon side to see if (2) is possible, that would be helpful.

**Comment by JohanLorenzo** [comment]
Status update: I met up with @mathjazz yesterday. He told me the Pontoon migration could be done next week. That said, the fewer steps we do during the migration from https://github.com/mozilla-mobile/android-components/ to https://github.com/mozilla-mobile/firefox-android, the better. Thus, we agreed to do @flodolo's suggestion: 

> Ideally, automation should keep using the existing TOML files and paths.

That's what https://github.com/mozilla-l10n/android-l10n-tooling/pull/48 is about. I managed to hack my way around to generate https://github.com/mozilla-l10n/android-l10n/pull/516 which kept the existing files and paths. 

Hence, let's go with @escapewindow's option 1: 

> 1. we may be able to hack around the paths on the android-l10n-tooling side 

I'm closing this PR since we don't need it anymore.

**Pull request closed without merging**
